### ISSUE TITLE
Plando generation with warpsong shuffle/spawn location shuffle frequently fails in 6.0.48+ but same input works in 6.0 stable

### ISSUE THREAD

**Issue by dewiniaid** [TestRunnerSRL/OoT-Randomizer#1300]
It looks like there was a regression added at some point during 6.x's development that causes seeds to fail to generate when entrances are plando'd.  This happens even if the entire set of entrances is sourced from a successfully generated non-plando spoiler log.

The [attached plando file](https://github.com/TestRunnerSRL/OoT-Randomizer/files/6448476/OoT_F47CE_NewPlando5_Spoiler.txt)
 (renamed from .json to .txt for Github) generates fine in the stable web generator (see https://ootrandomizer.com/seed/get?id=782037) but fails in dev_6.0.48 (see https://ootrandomizer.com/seed/get?id=782036).  This plando file originated from a regular spoiler log; some sections were removed for brevity.  This occurs 100% of attempts with this particular plando, and also fails with most other options for the randomized entrances.

This is the exact failure: 
```
'NoneType' object has no attribute 'connected_region'
Traceback (most recent call last):
  File "D:\git\OoT-Randomizer\OoTRandomizer.py", line 62, in start
    main(settings)
  File "D:\git\OoT-Randomizer\Main.py", line 56, in main
    spoiler = generate(settings, window=window)
  File "D:\git\OoT-Randomizer\Main.py", line 121, in generate
    worlds = build_world_graphs(settings, window=window)
  File "D:\git\OoT-Randomizer\Main.py", line 168, in build_world_graphs
    set_entrances(worlds)
  File "D:\git\OoT-Randomizer\EntranceShuffle.py", line 358, in set_entrances
    shuffle_random_entrances(worlds)
  File "D:\git\OoT-Randomizer\EntranceShuffle.py", line 464, in shuffle_random_entrances
    if entrance.replaces.connected_region and entrance.replaces.connected_region.name in regions:
AttributeError: 'NoneType' object has no attribute 'connected_region'
```

And the relevant code in `EntranceShuffle.py`:

```py
        for key, (regions, _) in priority_entrance_table.items():
            if key in one_way_priorities:
                for entrance in replaced_entrances:
                    if entrance.replaces.connected_region and entrance.replaces.connected_region.name in regions:
                        del one_way_priorities[key]
                        break
```

I'm not entirely certain what causes `entrance.replaces` to end up at `None`.  I did some further testing using this set of entrances:

```json
  "entrances":                 {
    "Prelude of Light Warp -> Temple of Time":                 {"region": "DMC Central Local", "from": "Bolero of Fire Warp"},
    "Bolero of Fire Warp -> DMC Central Local":                {"region": "Lon Lon Ranch", "from": "Hyrule Field"},
    "Minuet of Forest Warp -> Sacred Forest Meadow":           {"region": "Sacred Forest Meadow", "from": "Minuet of Forest Warp"},
    "Nocturne of Shadow Warp -> Graveyard Warp Pad Region":    {"region": "Graveyard Warp Pad Region", "from": "Nocturne of Shadow Warp"},
    "Requiem of Spirit Warp -> Desert Colossus":               {"region": "Desert Colossus", "from": "Requiem of Spirit Warp"},
    "Serenade of Water Warp -> Lake Hylia":                    {"region": "Lake Hylia", "from": "Serenade of Water Warp"}
  }
```

and only the `Hyrule Field -> Lon Lon Ranch` entrance ended up with `entrance.replaces is None`.  Continuing with this set of entrances, I tried modifying the if statement to guard against this case (`if entrance.replaces and entrance.replaces.connected_region...`) which suppressed this error but would cause a later error when trying to place priority entrances slightly further down the code:

```python
# [01:34:12] Failed attempt 10 of 10: Priority one-way entrance placement attempt count exceeded for world 0
        shuffle_one_way_priority_entrances(worlds, world, one_way_priorities, one_way_entrance_pools, one_way_target_entrance_pools, locations_to_ensure_reachable, complete_itempool, retry_count=2)
```

Interestingly, the entrance that could not be placed was the Bolero warp point (_despite it being explicitly specified as where Prelude goes_).

If Bolero is vanilla (e.g. I swap Prelude and Bolero in the above entrance list), generation succeeds -- though I did not test the resulting ROM to see if the songs actually worked as expected

As a reminder, this was a nonissue in 6.0 stable, so can be considered a regression.  I've successfully built a plando with heavily modified warpsong shuffles on Roman's branch back in May 2020 as well.  (Warpsong destination shuffle wasn't an option in official at that time.)  Current Roman's also has this issue.
